version: '3.8'

services:
  userauth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
      - "7001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=UserAuthDB;Username=postgres;Password=postgres123
      - Jwt__SecretKey=development-super-secret-jwt-key-that-is-at-least-32-characters-long
      - Jwt__Issuer=UserAuthAPI
      - Jwt__Audience=UserAuthAPI-Client
      - Jwt__ExpirationMinutes=60
      - Google__ClientId=your-google-client-id.googleusercontent.com
    depends_on:
      - postgres
    volumes:
      - ~/.aspnet/https:/https:ro

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: UserAuthDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: